services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    ChatBundle\:
        resource: '../src'
        exclude:
            - '../src/{DependencyInjection,Entity}'
            
    ChatBundle\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']